### ISSUE TITLE
Errors in newer upgrades

### ISSUE THREAD

**Issue by llSiddharthll** [OE-LUCIFER/Webscout#1]
1. In latest Gemini function it responds with two outputs which are exactly same, need improvement
2. In You Chat it returns correct response on local host or when used locally but it doesn't responds correctly for projects in production or any other domain
3. The Yep chat provides the correct response but it shows the same response three times, code needs improvements
4. Looking forward to work with you and add the text to image generation and other models in it.

**Comment by OE-LUCIFER** [comment]
Ok bro I will try to solve it  also gemini and you.com will only work as locally because they need to extract cookies from their sites respectively
