### ISSUE TITLE
Problem with python -m webscout answers -k Text

### ISSUE THREAD

**Issue by Processori7** [OE-LUCIFER/Webscout#19]
**Describe the bug**
[ERROR] Error in answers search: WEBS.answers() takes 2 positional arguments but 6 were given
Error: WEBS.answers() takes 2 positional arguments but 6 were given

**To Reproduce**
1. Paste in terminal: python -m webscout answers -k Text
2. See error

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by OE-LUCIFER** [comment]
Thank you, I have resolved the issue.
