### ISSUE TITLE
Problem with python -m webscout.webai webai --provider "phind" --rawdog

### ISSUE THREAD

**Issue by Processori7** [OE-LUCIFER/Webscout#20]
**Describe the bug**
If I use python -m webscout.webai webai --provider "phind" --rawdog in CMD, I see: 
python.exe: No module named webscout.webai

**To Reproduce**
1. Paste in terminal python -m webscout.webai webai --provider "phind" --rawdog
2. See error: No module named webscout.webai

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by OE-LUCIFER** [comment]
WebAI has been removed, and I forgot to update the README, but I have fixed it.
