### ISSUE TITLE
Request for credit/attribution

### ISSUE THREAD

**Issue by ddh0** [OE-LUCIFER/Webscout#9]
Hi!

I am Dylan Halladay, the author of the [easy-llama](https://github.com/ddh0/easy-llama) python package. I see you have copied lots of my code, as evidenced in the files under `/webscout/Local/` in this repo. While this is perfectly acceptable, I would like to kindly request that you credit me for my work somewhere in your README. Of course it's your choice whether you do so or not, but I think it would be polite.

In any case, thank you for your time.

**Comment by OE-LUCIFER** [comment]
my friend added it but don't worry I will give you credit for that @ddh0
